spring.application.name=tea_backend

# 1. Connection URL (From your Transaction Pooler screenshot)
# We added 'jdbc:' at the start and '?sslmode=require' at the end for Java

# Change this line ONLY (Add &prepareThreshold=0 at the end)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

# It is LONG because it includes your project ID
spring.datasource.username=postgres.hipkrdtfkamsbwjbtsat

# 3. Database Password

spring.datasource.password=mitvy6-bAznat-jytsiq

# Driver and JPA settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Supabase Configuration
SUPABASE_URL=https://nxdbtwzmotmxfpkwvfoq.supabase.co
SUPABASE_PUBLISHABLE_KEY=sb_publishable_hpHN2Y3hoTcEXIADTjofuQ_ooXAvG1s
SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
SUPABASE_JWKS_URL=https://nxdbtwzmotmxfpkwvfoq.supabase.co/auth/v1/.well-known/jwks.json